### ISSUE TITLE
[Feature request] Next/prev preset and next/prev instrument buttons

### ISSUE THREAD

**Issue by sewkokot** [robert-rc2i/ptq-client-webapp#9]
Thank you for developing and sharing this very useful app. I confirm it works well :)

Being new to Pianoteq I'm missing the next/prev preset and next/prev instrument buttons similar to the arrows in the official Pianoteq GUI. Such buttons would simplify exploring the instruments and presets.

**Comment by robert-rc2i** [comment]
Agrée, as it would enhance the user experience by not going through the menu navigation.  Thx for the suggestion, I’ll look into it

**Comment by robert-rc2i** [comment]
@sewkokot

I have merged the changes into release-1.1.0.  If you are familiar with git, you can test that branch on your setup and let me know how it works for you.  On my side all is fine so far.  This branch also has Metronome and better handling of the New midi sequencer API.

I'll be merging this release by the end of this week into the main branch.

**Comment by sewkokot** [comment]
Thank you very much! I will test that branch tomorrow and let you know :)

**Comment by sewkokot** [comment]
@robert-rc2i, I have tested the branch and confirm that the `prevPreset()` and `nextPreset()` work well as expected :) One additional improvement for me would be to have similar buttons using the `nextInstrument()` and `prevInstrument()` functions, this way I could select instruments without going into the menu which doesn't work reliably. Both on my laptop and smartphone in the browser I have to click many times to have the menu window open.

**Comment by robert-rc2i** [comment]
Humm, I am going to have to think on that one as the real estate of the header is quite high right now.  So adding another row would reduce the space of the actual control of the instrument.  I'll think about it.

As for the menu button, that's odd what you are experiencing, since this is just a click event.  Can you share your browser of choice and its version?  Also the OS that you are using it with?

Thx

**Comment by sewkokot** [comment]
> Humm, I am going to have to think on that one as the real estate of the header is quite high right now. So adding another row would reduce the space of the actual control of the instrument. I'll think about it.

It could even be in one row, however on small width phones the buttons will be wrapped anyway. I agree it needs to be done wisely :)
 
> As for the menu button, that's odd what you are experiencing, since this is just a click event. Can you share your browser of choice and its version? Also the OS that you are using it with?

I experience this on Rasberry Pi 400 latest Chromium and on my phone's Chrome 97.0.4692.98 under Android (and the same happens on another web browser on that phone).

What I also noticed is that short clicks open and close the menu immediately, while a long press (over 1 second) on the menu button leaves the menu window open.

Also thank you for developing such a useful app and your devoted time!

**Comment by sewkokot** [comment]
@robert-rc2i, Another finding: when removing the `onTouchEnd` option from the following line in Layouts.js, then the menu shows as expected (without hiding). 

`                <Button title="Menu" className="mx-2 mb-2 px-2 py-0" onClick={toggleMenu}><strong><i className="bi bi-list" /></strong> Menu</Button>`

**Comment by robert-rc2i** [comment]
Yep indeed.  This event handling is not necessary for Button.  But I had to include it on sliders, otherwise it was not working for that control on iOS.  I removed _onTouchEnd_ from the Midi and Metronome button also.  Can you check on Chrome and Android?

Thanks for participating!

**Comment by sewkokot** [comment]
I have checked the updated branch and now the menu button works well when clicking and tapping on Chrom/Chromium and Android. Thank you!
